version: "3"

services: 
    mobile:
        image: yangzhou301/lab-android
        container_name: mobile
        privileged: true
        restart: on-failure
        ports: 
            - "6080:6080"
            - "5554:5554"
            - "5555:5555"
        environment:
            - DEVICE=Nexus S
