version: "3"

services: 
    Victim:
        image: budtmo/docker-android-x86-7.1.1
        privileged: true 
        container_name: victim
        ports: 
            - "6080:6080"
            - "5554:5554"
            - "5555:5555"
        environment:
            - DEVICE=Nexus 5
        networks: 
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
    
    Attack:
        image: yangzhou301/lab7
        container_name: attack
        build: .
        tty: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.7

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config: 
                - subnet: 10.9.0.0/24


